import React from 'react';
import { Button, DataTable, Donut, FilterField, MetricCard, PageHeader, Pagination, Panel, SearchField } from '../components/UI';
import { receivableRows } from '../data';
import { Icon } from '../icons';

export default function AccountsReceivablePage(){const rows=receivableRows.map(r=>[...r,<button className="small-icon"><Icon name="more" size={15}/></button>]);return <>
 <PageHeader title="Accounts Receivable" subtitle="Track customer balances and money still owed to SomWay." actions={<><Button variant="secondary" icon="download">Export</Button><Button icon="plus">New Invoice</Button></>}/>
 <div className="content-grid">
  <div className="stack"><Panel><div className="filter-row" style={{margin:0}}><FilterField label="Branch" value="All Branches" icon="building"/><FilterField label="Service" value="All Services" icon="briefcase"/><FilterField label="Currency" value="All Currencies" icon="money"/><FilterField label="Payment status" value="Outstanding" icon="wallet"/><FilterField label="Aging" value="All Ages" icon="clock"/><SearchField placeholder="Search customer..."/><FilterField label="From" value="mm/dd/yyyy" icon="calendar"/><FilterField label="To" value="mm/dd/yyyy" icon="calendar"/></div></Panel>
  <div className="metrics-grid six"><MetricCard icon="money" label="Total Receivables (USD)" value="18,420" delta="↑ 8.7%" tone="blue"/><MetricCard icon="money" label="Total Receivables (KES)" value="2,145,300" delta="↑ 12.4%" tone="cyan"/><MetricCard icon="receipt" label="Outstanding Records" value="126" delta="↑ 9.3%" tone="violet"/><MetricCard icon="calendar" label="Due This Week" value="24,560" delta="↑ 6.2%" tone="orange"/><MetricCard icon="alert" label="Overdue Balances" value="56,780" delta="↑ 14.1%" tone="red"/><MetricCard icon="trend" label="Collection Rate" value="82.4%" delta="↑ 5.6%" tone="green"/></div>
  <Panel title="Receivables"><div className="filter-row" style={{justifyContent:'flex-end',marginTop:0}}><SearchField placeholder="Search by customer, invoice..."/><Button variant="secondary" icon="filter">Filters</Button></div><DataTable columns={['Customer','Service','Office/Branch','Invoice / Reference','Due Date','Amount','Paid','Outstanding','Status','Aging','Actions']} rows={rows}/><Pagination/></Panel></div>
  <div className="stack"><Panel title="Aging Summary (USD)"><Donut total="18,420" centerLabel="Total" segments={[{value:45,color:'#0b66e3',label:'Current (0–30)',amount:'USD 8,322'},{value:24,color:'#00a9c7',label:'31–60 Days',amount:'USD 4,344'},{value:16,color:'#16a34a',label:'61–90 Days',amount:'USD 2,910'},{value:8,color:'#f59e0b',label:'91–120 Days',amount:'USD 1,545'},{value:7,color:'#ef4444',label:'120+ Days',amount:'USD 1,288'}]}/></Panel>
  <Panel title="Top Customers (Outstanding)"><div className="stack">{[['Abdi Wholesale Ltd','USD 4,250',92],['Horizon Group','USD 3,860',82],['SomTech Solutions','USD 2,980',64],['Blue Ocean Ltd','USD 2,650',54],['BuildPlus Ltd','USD 1,950',42]].map((x,i)=><div key={x[0]}><div style={{display:'flex',justifyContent:'space-between',fontSize:10}}><span>{i+1}. {x[0]}</span><b>{x[1]}</b></div><div className="progress" style={{marginTop:7}}><i style={{width:`${x[2]}%`}}/></div></div>)}</div></Panel></div>
 </div>
 </>}
