import React from 'react';
import { Button, DataTable, Field, FormGrid, PageHeader, Panel } from '../components/UI';

export default function AdvancedSettingsPage(){return <>
 <PageHeader title="Advanced Settings" subtitle="Configure critical operational settings and financial parameters." actions={<Button icon="download">Save All Changes</Button>}/>
 <Panel title="Backup & Recovery" subtitle="Download business records and configuration. Staff passwords and active sessions are never included." actions={<div className="action-group"><Button icon="download">Download Backup</Button><Button variant="secondary" icon="upload">Choose Backup</Button></div>}><div className="mini-kpi" style={{maxWidth:330}}><span>Your data is secure</span><strong style={{fontSize:13}}>Backups are encrypted and stored securely.</strong><div className="muted" style={{marginTop:8}}>Last backup: May 12, 2026 at 08:45 AM</div></div></Panel>
 <Panel title="Cargo Pricing" subtitle="Set default cargo rate per kilogram between offices."><FormGrid><Field label="Origin Office" value="Mogadishu Office"/><Field label="Destination Office" value="Nairobi Office"/><Field label="Currency" value="USD"/><Field label="Rate per kilogram" placeholder="Enter rate"/></FormGrid><div className="modal-actions"><Button variant="secondary">Save Rate</Button></div></Panel>
 <Panel title="Starting Balances" subtitle="Set opening balances by office, payment channel and currency."><FormGrid><Field label="Office" value="Mogadishu Office"/><Field label="Payment Channel" value="EVC Plus"/><Field label="Currency" value="USD"/><Field label="Opening Float" placeholder="Enter opening float"/></FormGrid><div style={{marginTop:14}}><DataTable columns={['Office','Payment Channel','Currency','Opening Float','Actions']} rows={[["Nairobi",'M-Pesa','KES','KES 30,000',<Button variant="ghost" icon="edit">Edit</Button>],["Nairobi",'Cash','KES','KES 20,000',<Button variant="ghost" icon="edit">Edit</Button>],["Mogadishu",'Bank Transfer','USD','USD 1,250',<Button variant="ghost" icon="edit">Edit</Button>],["Mogadishu",'Cash','USD','USD 750',<Button variant="ghost" icon="edit">Edit</Button>]]}/></div></Panel>
 </>}
