import React from 'react';
import { BarChart, Button, Donut, MetricCard, PageHeader, Panel, FilterField, StatusBadge } from '../components/UI';
import { Icon } from '../icons';

export default function DailySummaryPage(){
 return <>
  <PageHeader title="Daily Summary" subtitle="Business-day reporting and daily closing." actions={<Button icon="download" variant="secondary">Export Summary</Button>}/>
  <div className="filter-row"><FilterField label="Business Date" value="May 12, 2025" icon="calendar"/><FilterField label="Branch" value="All Branches" icon="building"/><FilterField label="Currency" value="All Currencies" icon="money"/></div>
  <div className="content-grid">
   <div className="stack"><div className="metrics-grid"><MetricCard icon="wallet" label="Opening Balance" value="KES 520,000" tone="blue" foot="USD 6,540"/><MetricCard icon="money" label="Total Revenue" value="KES 1,245,000" delta="↑ 18.6%" tone="blue" foot="USD 15,420"/><MetricCard icon="wallet" label="Money Received" value="KES 985,500" delta="↑ 15.1%" tone="green" foot="USD 12,320"/><MetricCard icon="receipt" label="Total Expenses" value="KES 438,200" delta="↑ 8.7%" tone="orange" foot="USD 5,420"/></div>
   <div className="metrics-grid"><MetricCard icon="trend" label="Total Profit" value="KES 807,300" delta="↑ 21.3%" tone="violet" foot="USD 10,000"/><MetricCard icon="wallet" label="Accounts Receivable" value="KES 1,820,500" delta="↑ 12.4%" tone="cyan"/><MetricCard icon="receipt" label="Accounts Payable" value="KES 620,300" delta="- 6.1%" tone="pink"/><MetricCard icon="money" label="Expected Closing" value="KES 1,327,300" tone="blue" foot="USD 16,540"/></div>
   <div className="split-3"><Panel title="Revenue by Service (Today)"><Donut total="1,245,000" centerLabel="KES" segments={[{value:45,color:'#0b66e3',label:'Ticketing'},{value:32,color:'#00a9c7',label:'Cargo'},{value:16,color:'#16a34a',label:'Visa'},{value:7,color:'#f59e0b',label:'Other'}]}/></Panel><Panel title="Collections vs Expenses"><BarChart values={[10,22,38,55,62,68]} labels={['12 AM','4 AM','8 AM','12 PM','4 PM','8 PM']} dual/></Panel><Panel title="Branch Performance"><div className="stack">{[['Nairobi','762,300','512,200'],['Mogadishu','245,800','152,400']].map((r,i)=><div key={r[0]} style={{display:'grid',gridTemplateColumns:'1fr auto',gap:8,padding:'10px 0',borderBottom:'1px solid #edf1f6'}}><div><strong style={{fontSize:10}}>{r[0]}</strong><div className="muted">Revenue KES {r[1]}</div></div><div><span className="money-positive">KES {r[2]}</span><div className="muted">Profit</div></div></div>)}</div></Panel></div>
   </div>
   <div className="stack"><Panel title="Daily Closing Checklist" actions={<b style={{fontSize:10}}>5 / 8 Completed</b>}><div className="progress"><i style={{width:'62%'}}/></div><div className="stack" style={{marginTop:10}}>{['Reconcile cash and bank','Verify collections','Confirm expenses','Reconcile accounts receivable','Reconcile accounts payable','Review today’s bookings','Generate daily reports','Close business day'].map((t,i)=><div key={t} style={{display:'grid',gridTemplateColumns:'22px 1fr auto',alignItems:'center',gap:8}}><div className={`metric-icon tone-${i<4?'green':i<6?'orange':'blue'}`} style={{width:22,height:22,borderRadius:7}}><Icon name={i<4?'check':'clock'} size={12}/></div><span style={{fontSize:10}}>{t}</span><StatusBadge tone={i<4?'green':i<6?'orange':'blue'}>{i<4?'Done':'Open'}</StatusBadge></div>)}</div></Panel>
   <Panel title="Today’s Activity Timeline"><div className="timeline">{[['Opening balance recorded','08:02 AM'],['Cash reconciliation completed','09:15 AM'],['Payment received – USD 1,250','10:32 AM'],['Expense recorded – KES 12,500','11:45 AM'],['Daily summary generated','04:55 PM']].map((x,i)=><div className="timeline-row" key={i}><i className="timeline-dot"><Icon name={i<2?'check':'money'} size={12}/></i><div><strong>{x[0]}</strong><span>{i===4?'System':'Macruf Ahmed'}</span></div><time>{x[1]}</time></div>)}</div></Panel></div>
  </div>
 </>
}
