import React from 'react';
import { BarChart, Button, DataTable, Donut, FilterField, MetricCard, PageHeader, Pagination, Panel, SearchField } from '../components/UI';
import { expenseRows } from '../data';
import { Icon } from '../icons';

export default function ExpensesPage(){ const rows=expenseRows.map(r=>[...r,<div className="action-group"><button className="small-icon"><Icon name="eye" size={15}/></button><button className="small-icon"><Icon name="edit" size={15}/></button><button className="small-icon"><Icon name="more" size={15}/></button></div>]); return <>
 <PageHeader title="Expenses" subtitle="Review branch spending and profit-and-loss treatment." actions={<Button icon="plus">New Expense</Button>}/>
 <div className="metrics-grid"><MetricCard icon="wallet" label="Total Expenses" value="USD 66,540" delta="↑ 18.6%" tone="blue"/><MetricCard icon="check" label="Approved Expenses" value="USD 48,620" delta="↑ 16.2%" tone="green"/><MetricCard icon="clock" label="Pending Review" value="USD 12,420" delta="↑ 8.7%" tone="orange"/><MetricCard icon="briefcase" label="Most Used Category" value="Office Rent" tone="violet" foot="USD 18,260 (27.4%)"/></div>
 <div className="split-3" style={{marginTop:14}}><Panel title="Expenses by Category"><Donut total="66,540" centerLabel="USD" segments={[{value:27,color:'#0b66e3',label:'Office Rent'},{value:23,color:'#16a34a',label:'Salaries'},{value:17,color:'#7c3aed',label:'Travel & Transport'},{value:10,color:'#f59e0b',label:'Marketing'},{value:23,color:'#2daec4',label:'Other'}]}/></Panel><Panel title="Monthly Expense Trend"><BarChart values={[20,35,60,44,50,68,54,72,61,70,75,80]} labels={['J','F','M','A','M','J','J','A','S','O','N','D']}/></Panel><Panel title="Expenses by Branch"><div className="stack">{[['Nairobi','40,250',76],['Mogadishu','14,620',52]].map(r=><div key={r[0]}><div style={{display:'flex',justifyContent:'space-between',fontSize:10}}><strong>{r[0]}</strong><span>USD {r[1]}</span></div><div className="progress" style={{marginTop:7}}><i style={{width:`${r[2]}%`}}/></div></div>)}</div></Panel></div>
 <div className="filter-row"><SearchField placeholder="Search expenses..."/><FilterField value="All Branches" icon="building"/><FilterField value="All Categories" icon="filter"/><FilterField value="All Payment Methods" icon="wallet"/><FilterField value="All Currencies" icon="money"/><FilterField value="All Statuses" icon="check"/></div>
 <Panel title="Expense Register"><DataTable columns={['Date','Office','Category','Description','Payment','Amount','Status','P&L','Actions']} rows={rows}/><Pagination/></Panel>
 </> }
