import React from 'react';
import { Button, Field, FormGrid } from '../components/UI';
import { Icon } from '../icons';
import { TrackingResult } from './TrackingPage';

export default function PublicLandingPage(){return <div className="public-page">
 <nav className="public-nav"><img src="/somway-logo.png" alt="SomWay"/><div className="public-links"><a className="active" href="#home">Home</a><a href="#services">Services</a><a href="#tracking">Cargo Tracking</a><a href="#tracking">Visa Tracking</a><a href="#branches">Branches</a><a href="#contact">Contact</a><Button icon="box">Track Shipment</Button></div></nav>
 <section className="hero" id="home"><div className="hero-copy"><span className="chip">● Welcome to SomWay</span><h1>Your trusted partner for <span>travel, cargo and visa</span> services.</h1><p>From air ticketing to secure cargo shipping and visa processing, SomWay connects Nairobi and Mogadishu with fast, reliable and professional service.</p><div className="hero-actions"><Button icon="box">Track Cargo</Button><Button variant="secondary" icon="passport">Track Visa</Button></div><div className="trust-chips"><span>✓ Fast & Reliable</span><span>✓ Secure Handling</span><span>✓ Real-time Tracking</span><span>✓ Customer Support</span></div></div><div className="hero-art"><div className="globe-orb"></div><div className="float-plane">✈</div><div className="float-truck">🚚</div><div className="float-boxes"></div></div></section>
 <section className="public-section" id="services"><div className="section-title"><h2>Our Services</h2><p>Professional solutions for travel, cargo and visa needs.</p></div><div className="services-grid"><Service icon="plane" title="Air Ticketing" text="Domestic and international flight booking, changes, rebooking and customer support." action="Book Now"/><Service icon="box" title="Cargo Shipping" text="Secure cargo intake, pricing, tracking, arrival, collection and delivery coordination." action="Ship Cargo"/><Service icon="passport" title="Visa Processing" text="Application intake, document tracking, payment monitoring and status communication." action="Track Visa"/><Service icon="headset" title="Travel Assistance" text="Professional support from both Nairobi and Mogadishu offices." action="Contact Support"/></div></section>
 <section className="tracking-public" id="tracking"><div className="panel-head" style={{marginBottom:16}}><div><h3 style={{fontSize:22}}>Tracking Centre</h3><p style={{color:'#b7cae5'}}>Track your cargo shipments and visa applications in real time.</p></div><div className="subtabs" style={{margin:0}}><button className="active">Cargo Shipment</button><button>Visa Application</button></div></div><div style={{display:'grid',gridTemplateColumns:'1fr 120px',gap:10,marginBottom:14}}><div className="search-field"><Icon name="search"/><span>CGO-MOG-20260901-0013</span></div><Button>Search</Button></div><TrackingResult dark/></section>
 <section className="public-section" id="branches"><div className="section-title"><h2>Our Branches</h2><p>Visit or contact SomWay in Nairobi or Mogadishu.</p></div><div className="public-branches"><Branch city="Mogadishu Office" address="KM5, Hodan District, Mogadishu, Somalia" phone="+252 61 123 4567" email="mogadishu@somway.com"/><Branch city="Nairobi Office" address="Nairobi, Kenya" phone="+254 712 345 678" email="nairobi@somway.com"/></div></section>
 <section className="public-section" id="contact"><div className="contact-grid"><div className="contact-card"><h3>Get in Touch</h3><p>Have questions or need assistance? Our team can help with visa, tickets and cargo.</p><div className="stack" style={{marginTop:16}}><Contact icon="phone" text="+252 61 123 4567"/><Contact icon="mail" text="support@somway.com"/><Contact icon="clock" text="Sat–Thu • 8:00 AM – 6:00 PM"/></div></div><div className="contact-card"><FormGrid><Field label="Full Name" placeholder="Your full name"/><Field label="Email Address" placeholder="you@email.com"/><Field label="Phone Number" placeholder="+252 / +254"/><Field label="Service" value="Select a service" full/><Field label="Message" placeholder="How can we help you?" full/></FormGrid><div className="modal-actions"><Button icon="mail">Send Message</Button></div></div><div className="contact-card whatsapp"><Icon name="headset" size={52}/><div><h3>Need immediate help?</h3><p style={{color:'#c9dbef'}}>Chat with our support team on WhatsApp.</p></div><Button variant="secondary" icon="phone">Chat on WhatsApp</Button></div></div></section>
 <footer className="public-footer"><div><img src="/somway-logo.png" alt="SomWay"/><p>SomWay Travel & Logistics is your trusted partner for travel, cargo and visa services. We deliver your world with care.</p></div><div><h4>Quick Links</h4><a>Home</a><a>About Us</a><a>Track Shipment</a><a>Contact</a></div><div><h4>Our Services</h4><a>Air Ticketing</a><a>Cargo Shipping</a><a>Visa Processing</a><a>Travel Assistance</a></div><div><h4>Contact Us</h4><p>Mogadishu • +252 61 123 4567</p><p>Nairobi • +254 712 345 678</p><p>support@somway.com</p></div><div className="footer-bottom"><span>© 2026 SomWay Travel & Logistics. All rights reserved.</span><span>Privacy Policy &nbsp; • &nbsp; Terms & Conditions</span></div></footer>
 </div>}
function Service({icon,title,text,action}:{icon:any;title:string;text:string;action:string}){return <div className="service-card"><div className="service-icon"><Icon name={icon}/></div><h3>{title}</h3><p>{text}</p><a>{action} <Icon name="arrow" size={14}/></a></div>}
function Branch({city,address,phone,email}:{city:string;address:string;phone:string;email:string}){return <div className="branch-card"><div><h3>{city}</h3><p>{address}</p><p>☎ {phone}<br/>✉ {email}</p><div className="subtabs" style={{marginTop:13}}><button>Call</button><button>WhatsApp</button><button>Email</button></div></div><div className="image"></div></div>}
function Contact({icon,text}:{icon:any;text:string}){return <div style={{display:'flex',gap:9,alignItems:'center',fontSize:10}}><Icon name={icon} size={16} className="linkish"/>{text}</div>}
