import React from 'react';
import { Button, PageHeader, Panel, SearchField, StatusBadge } from '../components/UI';
import { Icon } from '../icons';

export default function ReceiptsPage(){return <>
 <PageHeader title="Receipt Builder" subtitle="Find any ticket, visa or cargo transaction, then generate and download a PDF receipt."/>
 <div className="kpi-strip" style={{maxWidth:820,marginLeft:'auto',marginBottom:14}}><div className="mini-kpi"><span>Receipts Generated Today</span><strong>24 <span className="positive" style={{display:'inline'}}>↑ 20%</span></strong></div><div className="mini-kpi"><span>Pending Receipts</span><strong>7</strong></div><div className="mini-kpi"><span>Last Transaction</span><strong style={{fontSize:13}}>TKT/250531/0012</strong></div></div>
 <div className="split-2">
  <div className="stack"><Panel title="Find a Transaction" subtitle="Search by ticket, visa, or cargo reference to generate a receipt."><SearchField placeholder="Enter reference (e.g. TKT/250531/0012, VISA/250531/0008, CRG/250531/0004)"/><div className="subtabs" style={{marginTop:12}}><button>TKT/250531/0012</button><button>VISA/250531/0008</button><button>CRG/250531/0004</button></div><div className="panel" style={{boxShadow:'none',marginTop:8}}><h3 style={{fontSize:13}}>Accepted Records</h3>{[['ticket','Ticket booking reference','Air ticket bookings and reservations'],['passport','Visa application reference','Visa application and processing'],['box','Cargo tracking number','Cargo shipments and deliveries']].map(x=><div key={x[1]} style={{display:'grid',gridTemplateColumns:'34px 1fr',gap:9,marginTop:12}}><div className="metric-icon tone-blue" style={{width:34,height:34}}><Icon name={x[0] as any} size={16}/></div><div><strong style={{fontSize:10}}>{x[1]}</strong><div className="muted">{x[2]}</div></div></div>)}</div></Panel>
  <Panel title="Recent References"><div className="stack">{[['TKT/250531/0012','Ahmed Hassan','Ticketed'],['VISA/250531/0008','Amina Yusuf','Issued'],['CRG/250531/0004','BuildPlus Ltd','Delivered']].map((x,i)=><div key={x[0]} style={{display:'grid',gridTemplateColumns:'34px 1fr auto',gap:9,alignItems:'center'}}><div className={`metric-icon tone-${i===0?'blue':i===1?'cyan':'orange'}`} style={{width:34,height:34}}><Icon name={i===0?'ticket':i===1?'passport':'box'} size={16}/></div><div><strong style={{fontSize:10}}>{x[0]}</strong><div className="muted">{x[1]}</div></div><StatusBadge tone={i===2?'green':'blue'}>{x[2]}</StatusBadge></div>)}</div></Panel></div>
  <Panel title="Receipt Preview" actions={<><Button variant="ghost" icon="receipt">Print</Button><Button variant="ghost" icon="download">Download PDF</Button><Button variant="ghost" icon="mail">Share / Email</Button></>}>
    <div style={{border:'1px solid #dfe7f2',borderRadius:14,padding:26,minHeight:610,background:'#fff'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start'}}><img src="/somway-logo.png" alt="SomWay" style={{width:160,height:70,objectFit:'contain'}}/><div style={{textAlign:'right'}}><h2>Receipt</h2><strong>#RCPT/250531/0012</strong><div className="muted">May 31, 2025 • 10:42 AM</div></div></div><hr style={{border:0,borderTop:'1px dashed #dce5ef',margin:'22px 0'}}/><div className="split-even"><div><h3 style={{fontSize:12}}>Customer Details</h3><p className="muted" style={{marginTop:10,lineHeight:1.9}}>Customer Name<br/><b style={{color:'#243653'}}>Ahmed Hassan</b><br/>Email<br/><b style={{color:'#243653'}}>ahmed.hassan@email.com</b><br/>Phone<br/><b style={{color:'#243653'}}>+254 712 345 678</b></p></div><div><h3 style={{fontSize:12}}>Service Details</h3><p className="muted" style={{marginTop:10,lineHeight:1.9}}>Service Type<br/><b style={{color:'#243653'}}>Air Ticket</b><br/>Route<br/><b style={{color:'#243653'}}>NBO → DXB</b><br/>Travel Date<br/><b style={{color:'#243653'}}>May 20, 2025</b></p></div></div><hr style={{border:0,borderTop:'1px dashed #dce5ef',margin:'22px 0'}}/><div className="split-even"><div><h3 style={{fontSize:12}}>Payment Information</h3><p className="muted" style={{marginTop:10,lineHeight:1.9}}>Payment Method<br/><b style={{color:'#243653'}}>VISA Card</b><br/>Transaction ID<br/><b style={{color:'#243653'}}>TXN/250531/8891</b></p><StatusBadge tone="green">Payment Successful</StatusBadge></div><div><h3 style={{fontSize:12}}>Payment Summary</h3><div style={{display:'grid',gridTemplateColumns:'1fr auto',gap:10,fontSize:11,marginTop:12}}><span>Base Fare</span><b>USD 60,000</b><span>Taxes & Fees</span><b>USD 4,540</b><span>Service Fee</span><b>USD 2,000</b><strong style={{fontSize:14}}>Total Paid</strong><strong style={{fontSize:20,color:'#0b66e3'}}>USD 66,540</strong></div></div></div></div>
  </Panel>
 </div>
 </>}
