import React from 'react';
import { Button, Field, FormGrid, PageHeader, Panel } from '../components/UI';
import { Icon } from '../icons';

export default function SettingsPage(){return <>
 <PageHeader title="Agency Settings" subtitle="Manage your agency profile, operational preferences, financial settings, and system configurations." actions={<Button icon="upload">Save All Changes</Button>}/>
 <div className="split-even"><Panel title="Identity" subtitle="Update agency information and contact details." actions={<Button variant="secondary" icon="upload">Change Logo</Button>}><FormGrid><Field label="Agency Name" value="SomWay Travel & Logistics" full/><Field label="Business Email" value="info@somway.com" icon="mail"/><Field label="Phone Number" value="+254 700 000 111" icon="phone"/><Field label="Website (Optional)" value="www.somway.com" icon="globe" full/></FormGrid><div className="modal-actions"><Button variant="secondary">Save</Button></div></Panel>
 <Panel title="Owner Security" subtitle="Keep your account secure by updating your password."><FormGrid><Field label="Current Password" placeholder="Enter current password" icon="lock" full/><Field label="New Password" placeholder="Enter new password" icon="lock"/><Field label="Confirm New Password" placeholder="Confirm new password" icon="lock"/></FormGrid><div className="modal-actions"><Button variant="secondary">Update Password</Button></div></Panel></div>
 <Panel title="Daily Summary Hours" subtitle="Set the business day timeframe used for daily summaries and closing processes." className="" ><FormGrid><Field label="Timezone" value="Africa/Mogadishu (EAT)"/><Field label="Business Day Start" value="07:00 AM" icon="clock"/><Field label="Business Day End" value="06:00 PM" icon="clock"/></FormGrid></Panel>
 <div className="split-even"><Panel title="Branch Defaults"><FormGrid><Field label="Default Branch" value="All branches" icon="building"/><Field label="Default Currency" value="USD / KES" icon="money"/><Field label="Default Country" value="Somalia / Kenya" icon="globe"/></FormGrid></Panel><Panel title="Payment Methods"><div className="subtabs"><button className="active">Cash</button><button className="active">Bank Transfer</button><button className="active">M-Pesa</button><button className="active">EVC Plus</button></div><FormGrid><Field label="Default Payment Term" value="Payment on Delivery"/><Field label="Invoice Currency" value="Same as transaction currency"/></FormGrid></Panel></div>
 <Panel title="Data Export & Backup"><div className="kpi-strip"><Button variant="secondary" icon="download">Export Agency Data</Button><Button variant="secondary" icon="download">Export Financial Reports</Button><Button variant="secondary" icon="database">Backup Database</Button><Button variant="secondary" icon="refresh">Schedule Automatic Backup</Button></div></Panel>
 </>}
