import React from 'react';
import { Button, DataTable, PageHeader, Panel, SearchField, StatusBadge } from '../components/UI';
import { Icon } from '../icons';

export default function TeamRolesPage(){const rows=[
 [member('AH','Abdulkadir Hassan','abdulkadir@somway.com'),<StatusBadge tone="blue">General Manager</StatusBadge>,<StatusBadge tone="green">Active</StatusBadge>,'Nairobi + Mogadishu','30 May 2026 10:24 AM',actions()],
 [member('MO','Macruf Ahmed','owner@somway.com'),<StatusBadge tone="green">Owner</StatusBadge>,<StatusBadge tone="green">Active</StatusBadge>,'All Branches','31 May 2026 11:03 AM',actions()],
 [member('NO','Nairobi Officer','nairobi@somway.com'),<StatusBadge tone="violet">Branch Operator</StatusBadge>,<StatusBadge tone="green">Active</StatusBadge>,'Nairobi','29 May 2026 09:52 AM',actions()],
 [member('MO','Mogadishu Officer','mogadishu@somway.com'),<StatusBadge tone="violet">Branch Operator</StatusBadge>,<StatusBadge tone="green">Active</StatusBadge>,'Mogadishu','30 May 2026 08:15 AM',actions()],
 ];return <>
 <PageHeader title="Team & Role Access" subtitle="Create staff accounts, assign roles, and control what team members can access." actions={<Button icon="plus">New Staff</Button>}/>
 <div className="split-3"><Role tone="green" title="Owner" tag="OWNER" body="Full control over all system settings, users, branches and data." bullets={['All permissions','Manage users & roles','View all branches & data','System configuration']}/><Role tone="blue" title="General Manager" tag="GENERAL MANAGER" body="Manage operations, staff and reports across both branches." bullets={['Manage bookings, cargo & clients','Approve requests & payments','View reports & analytics','Manage staff']}/><Role tone="violet" title="Branch Operator" tag="BRANCH OPERATOR" body="Handle daily tasks and operations within the assigned branch." bullets={['Create bookings & cargo','Manage clients & documents','Update shipment statuses','View branch-level reports']}/></div>
 <Panel title="All Staff" subtitle="Manage your team members and their access." actions={<><SearchField placeholder="Search by name, email or role..."/><Button variant="secondary" icon="filter">Filters</Button><Button variant="secondary" icon="download">Export</Button></>}><DataTable columns={['Staff Member','Role','Status','Assigned Branches','Last Login','Actions']} rows={rows}/></Panel>
 </>}
function member(initials:string,name:string,email:string){return <div style={{display:'flex',gap:9,alignItems:'center'}}><div className="avatar" style={{width:34,height:34,color:'#31537f',background:'#eef3fb'}}>{initials}</div><div><strong style={{fontSize:10}}>{name}</strong><div className="muted">{email}</div></div></div>}
function actions(){return <div className="action-group"><Button variant="ghost">Suspend</Button><Button variant="ghost" icon="lock">Reset Password</Button><Button variant="ghost" icon="route">Copy Link</Button></div>}
function Role({tone,title,tag,body,bullets}:{tone:string;title:string;tag:string;body:string;bullets:string[]}){return <Panel><div style={{display:'grid',gridTemplateColumns:'52px 1fr',gap:12}}><div className={`metric-icon tone-${tone}`} style={{width:52,height:52,borderRadius:18}}><Icon name={title==='Owner'?'shield':'users'} size={24}/></div><div><StatusBadge tone={tone as any}>{tag}</StatusBadge><h3 style={{fontSize:17,marginTop:7}}>{title}</h3><p style={{fontSize:10,color:'#687795',lineHeight:1.6,marginTop:5}}>{body}</p></div></div><div className="stack" style={{marginTop:14}}>{bullets.map(b=><div key={b} style={{display:'flex',gap:8,alignItems:'center',fontSize:10}}><Icon name="check" size={14} className="positive"/>{b}</div>)}</div></Panel>}
