import mongoose from "mongoose";

const cargoSchema = new mongoose.Schema(
  {
    id: { type: String, required: true, unique: true },
    tracking: { type: String, required: true },
    origin: { type: String, required: true },
    destination: { type: String, required: true },
    originBranchId: { type: mongoose.Schema.Types.ObjectId, ref: "Branch", default: null },
    destinationBranchId: { type: mongoose.Schema.Types.ObjectId, ref: "Branch", default: null },
    dateIn: { type: String, default: "" },
    sender: { type: String, default: "" },
    senderPhone: { type: String, default: "" },
    senderEmail: { type: String, default: "" },
    receiver: { type: String, default: "" },
    receiverPhone: { type: String, default: "" },
    receiverEmail: { type: String, default: "" },
    senderClientId: { type: mongoose.Schema.Types.ObjectId, ref: "Client", index: true, default: null },
    receiverClientId: { type: mongoose.Schema.Types.ObjectId, ref: "Client", index: true, default: null },
    senderNormalizedPhone: { type: String, default: "" },
    receiverNormalizedPhone: { type: String, default: "" },
    contents: { type: String, default: "" },
    weight: { type: Number, default: 0 },
    currency: { type: String, enum: ["KES", "USD"], required: true },
    rate: { type: Number, default: 0 },
    rateNote: { type: String, default: "" },
    cost: { type: Number, default: 0 },
    payType: { type: String, enum: ["Prepaid", "Collect"], required: true },
    paymentMethod: { type: String, enum: ["Cash", "M-Pesa", "Bank", "EVC Plus"], required: true },
    paymentMethodId: { type: mongoose.Schema.Types.ObjectId, ref: "PaymentMethod", default: null },
    paidByOffice: { type: String, required: true },
    paidByBranchId: { type: mongoose.Schema.Types.ObjectId, ref: "Branch", default: null },
    paid: { type: Boolean, default: false },
    paymentDate: { type: String, default: "" },
    status: { type: String, enum: ["received", "in_transit", "arrived", "ready_for_collection", "delivered", "cancelled", "claim", "In Transit", "Arrived", "Delivered", "Claim"], default: "received", index: true },
    statusHistory: [{
      event: { type: String, default: "" },
      fromStatus: { type: String, default: "" },
      toStatus: { type: String, default: "" },
      at: { type: String, default: "" },
      userId: { type: String, default: "" },
      userName: { type: String, default: "" },
      branchId: { type: mongoose.Schema.Types.ObjectId, ref: "Branch", default: null },
      note: { type: String, default: "" },
    }],
    receivedAt: { type: String, default: "" },
    receivedByUserId: { type: String, default: "" },
    dispatchedAt: { type: String, default: "" },
    dispatchedByUserId: { type: String, default: "" },
    arrivedAt: { type: String, default: "" },
    arrivedByUserId: { type: String, default: "" },
    readyForCollectionAt: { type: String, default: "" },
    readyForCollectionByUserId: { type: String, default: "" },
    deliveredAt: { type: String, default: "" },
    deliveredByUserId: { type: String, default: "" },
    cancelledAt: { type: String, default: "" },
    cancelledByUserId: { type: String, default: "" },
    cancellationReason: { type: String, default: "" },
    dateDelivered: { type: String, default: "" },
    notes: { type: String, default: "" },
    createdBy: { type: String, default: "" },
    updatedBy: { type: String, default: "" },
    updatedAt: { type: String, default: () => new Date().toISOString() },
  },
  { strict: true }
);

const Cargo = mongoose.models.Cargo || mongoose.model("Cargo", cargoSchema);

export default Cargo;
